spring.datasource.url=jdbc:postgresql://localhost:5432/homework_56
spring.datasource.username=app
spring.datasource.password=nopasswd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
